# Generated by Django 5.0.3 on 2024-03-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthqquser',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
